from __future__ import annotations
from typing import Protocol, Any
from .models import UserStory
class LLMPort(Protocol):
    model_name: str
    async def generate_json(self, *, system: str, user: str, schema: dict[str, Any]) -> dict[str, Any]: ...
class AuditPort(Protocol):
    async def append(self, event: Any) -> None: ...
class StoryRepository(Protocol):
    async def save(self, story: UserStory) -> UserStory: ...
    async def get(self, story_id: str) -> UserStory | None: ...
class AzureDevOpsPort(Protocol):
    async def publish_story(self, story: UserStory, *, project: str, mapping: dict[str, str], approval_id: str) -> dict[str, Any]: ...
    async def validate_pipeline(self, yaml_text: str) -> dict[str, Any]: ...
class CloudPort(Protocol):
    provider: str
    async def provision_isolated_performance_job(self, config: dict[str, Any]) -> dict[str, Any]: ...