CREATE TABLE vehicles (vehicle_id INTEGER PRIMARY KEY, model VARCHAR(100) NOT NULL, year INTEGER NOT NULL, price DECIMAL(12,2) NOT NULL, stock INTEGER NOT NULL);
CREATE TABLE dealers (dealer_id INTEGER PRIMARY KEY, name VARCHAR(150) NOT NULL, region VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL);
CREATE TABLE customers (customer_id INTEGER PRIMARY KEY, name VARCHAR(150) NOT NULL, email VARCHAR(200) NOT NULL);
CREATE TABLE inventory (inventory_id INTEGER PRIMARY KEY, vehicle_id INTEGER NOT NULL, dealer_id INTEGER NOT NULL, available BOOLEAN NOT NULL);
CREATE TABLE sales_orders (order_id INTEGER PRIMARY KEY, dealer_id INTEGER NOT NULL, vehicle_id INTEGER NOT NULL, customer_id INTEGER NOT NULL, status VARCHAR(30) NOT NULL, total DECIMAL(12,2) NOT NULL);
CREATE TABLE service_appointments (appointment_id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL, dealer_id INTEGER NOT NULL, status VARCHAR(30) NOT NULL);
CREATE TABLE parts (part_id INTEGER PRIMARY KEY, name VARCHAR(150) NOT NULL, stock INTEGER NOT NULL);
CREATE TABLE test_cases (case_id VARCHAR(80) PRIMARY KEY, scenario TEXT NOT NULL, expected_result TEXT NOT NULL);
